/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function sum(a: number, b: number): number
export const enum EmbeddingModel {
  /** sentence-transformers/all-MiniLM-L6-v2 */
  AllMiniLML6V2 = 0,
  /** Quantized sentence-transformers/all-MiniLM-L6-v2 */
  AllMiniLML6V2Q = 1,
  /** sentence-transformers/all-MiniLM-L12-v2 */
  AllMiniLML12V2 = 2,
  /** Quantized sentence-transformers/all-MiniLM-L12-v2 */
  AllMiniLML12V2Q = 3,
  /** BAAI/bge-base-en-v1.5 */
  BGEBaseENV15 = 4,
  /** Quantized BAAI/bge-base-en-v1.5 */
  BGEBaseENV15Q = 5,
  /** BAAI/bge-large-en-v1.5 */
  BGELargeENV15 = 6,
  /** Quantized BAAI/bge-large-en-v1.5 */
  BGELargeENV15Q = 7,
  /** BAAI/bge-small-en-v1.5 - Default */
  BGESmallENV15 = 8,
  /** Quantized BAAI/bge-small-en-v1.5 */
  BGESmallENV15Q = 9,
  /** nomic-ai/nomic-embed-text-v1 */
  NomicEmbedTextV1 = 10,
  /** nomic-ai/nomic-embed-text-v1.5 */
  NomicEmbedTextV15 = 11,
  /** Quantized v1.5 nomic-ai/nomic-embed-text-v1.5 */
  NomicEmbedTextV15Q = 12,
  /** sentence-transformers/paraphrase-MiniLM-L6-v2 */
  ParaphraseMLMiniLML12V2 = 13,
  /** Quantized sentence-transformers/paraphrase-MiniLM-L6-v2 */
  ParaphraseMLMiniLML12V2Q = 14,
  /** sentence-transformers/paraphrase-mpnet-base-v2 */
  ParaphraseMLMpnetBaseV2 = 15,
  /** BAAI/bge-small-zh-v1.5 */
  BGESmallZHV15 = 16,
  /** intfloat/multilingual-e5-small */
  MultilingualE5Small = 17,
  /** intfloat/multilingual-e5-base */
  MultilingualE5Base = 18,
  /** intfloat/multilingual-e5-large */
  MultilingualE5Large = 19,
  /** mixedbread-ai/mxbai-embed-large-v1 */
  MxbaiEmbedLargeV1 = 20,
  /** Quantized mixedbread-ai/mxbai-embed-large-v1 */
  MxbaiEmbedLargeV1Q = 21,
  /** Alibaba-NLP/gte-base-en-v1.5 */
  GTEBaseENV15 = 22,
  /** Quantized Alibaba-NLP/gte-base-en-v1.5 */
  GTEBaseENV15Q = 23,
  /** Alibaba-NLP/gte-large-en-v1.5 */
  GTELargeENV15 = 24,
  /** Quantized Alibaba-NLP/gte-large-en-v1.5 */
  GTELargeENV15Q = 25
}
export interface JsInitOptions {
  modelName?: EmbeddingModel
  maxLength?: number
  cacheDir?: string
  showDownloadProgress?: boolean
}
export type JsTextEmbedding = TextEmbedding
export declare class TextEmbedding {
  constructor(options: JsInitOptions)
  embed(texts: Array<string>, batchSize?: number | undefined | null): Array<Array<number>>
}
